using Microsoft.AspNetCore.Mvc.RazorPages;

namespace YoutubeToText.Pages.Learn;

public class FirmengrundsaetzeModel : PageModel
{
    public record Block(string De, string Ru);

    public List<Block> Blocks { get; } = new()
    {
        new("Bevor ein Unternehmen mit seinem Geschäft so richtig starten kann, muss es die Firmengrundsätze beachten.", "Прежде чем компания сможет по-настоящему начать деятельность, она должна учитывать принципы фирмы."),
        new("Was es damit auf sich hat, erfährst du jetzt.", "Что это значит, ты узнаешь сейчас."),
        new("Angenommen, du eröffnest eine Bäckerei.", "Предположим, ты открываешь пекарню."),
        new("Nennen wir sie Goldkruste.", "Назовём её «Гольдкрусте»."),
        new("Du hast das perfekte Rezept für knuspriges Brot, dein Team ist begeistert und du bist bereit loszulegen.", "У тебя идеальный рецепт хрустящего хлеба, команда в восторге, и ты готов стартовать."),
        new("Doch dann kommt die Frage, darf deine Bäckerei diesen Namen überhaupt tragen?", "Но затем возникает вопрос: может ли твоя пекарня вообще носить это название?"),
        new("Hier kommen die Firmengrundsätze ins Spiel.", "Здесь вступают в силу принципы фирмы."),
        new("Sie sind im Handelsgesetzbuch verankert und legen fest, welchen Namen ein Unternehmen führen darf.", "Они закреплены в Торговом кодексе и определяют, какое название может носить компания."),
        new("Denn der Firmenname ist das Aushängeschild deines Geschäfts.", "Ведь фирменное название — визитная карточка твоего бизнеса."),
        new("Er muss seriös und rechtlich einwandfrei sein.", "Оно должно быть серьёзным и юридически безупречным."),
        new("Für Kunden, Lieferanten und Behörden.", "Для клиентов, поставщиков и органов власти."),
        new("Damit das Gewährleistet ist, gibt es fünf Firmengrundsätze.", "Чтобы это было обеспечено, существует пять принципов фирмы."),
        new("Fangen wir mit dem ersten Grundsatz der Firmen Wahrheit an.", "Начнём с первого принципа — принципа истинности фирменного наименования."),
        new("Als Bäckermeister bist du stolz auf deine Backstube und möchtest sie etwas größer wirken lassen.", "Как мастер‑пекарь ты гордишься своей пекарней и хочешь, чтобы она выглядела немного крупнее."),
        new("Also überlegst du dir neue Namen.", "Поэтому ты придумываешь новые названия."),
        new("Goldkruste-Großbäckerei GmbH.", "«Гольдкрусте — крупная пекарня GmbH»."),
        new("Oder vielleicht sogar Dr. Mellas Feinkostbäckerei.", "Или даже «Доктор Мелла — деликатесная пекарня»."),
        new("Klingt professionell, ist aber nicht erlaubt.", "Звучит профессионально, но это недопустимо."),
        new("Denn hier greift der Grundsatz der Firmen Wahrheit.", "Здесь действует принцип истинности фирменного наименования."),
        new("Er steht in §18 HGB und stellt sicher, dass sein Firmenname Kunden oder Geschäftspartner nicht täuscht oder falsche Erwartungen weckt.", "Он закреплён в §18 HGB и гарантирует, что название не вводит клиентов или партнёров в заблуждение."),
        new("Der Name muss also zur Tätigkeit passen und darf keine falschen Angaben zurechts vormachen.", "Название должно соответствовать деятельности и не содержать ложных сведений."),
        new("Eine Dorfbäckerei darf sich daher nicht Großbäckerei nennen und der Zusatz GmbH im Namen wäre nur erlaubt, wenn der Inhaber auch tatsächlich eine GmbH führt.", "Поэтому сельская пекарня не может называться крупной, а приписка GmbH допустима лишь если владелец действительно ведёт GmbH."),
        new("Außerdem ist es nicht zulässig, sich mit akademischen Titeln zu schmücken, die der Inhaber gar nicht besitzt.", "Также нельзя использовать академические титулы, которыми владелец не обладает."),
        new("Der Name Dr. Mellas Feinkostbäckerei fällt also ebenfalls weg.", "Следовательно, название «Доктор Мелла — деликатесная пекарня» тоже отпадает."),
        new("Läuft deine Bäckerei aber richtig gut und du hast wirklich eine GmbH, kannst du das im Firmennamen erwähnen.", "Но если пекарня действительно успешна и у тебя есть GmbH, ты можешь указать это в названии."),
        new("Als GmbH kommt aber noch etwas auf dich zu.", "Однако как у GmbH появляется ещё одно требование."),
        new("Der Eintrag ins Handelsregister.", "Запись в торговом реестре."),
        new("Aber warum ist das notwendig?", "Но почему это нужно?"),
        new("Wegen dem Grundsatz der Firmen Öffentlichkeit.", "Из‑за принципа публичности фирмы."),
        new("Denn nach §29 HGB musst du als Unternehmen offiziell registriert und leicht überprüfbar sein.", "Согласно §29 HGB компания должна быть официально зарегистрирована и легко проверяема."),
        new("Im Handelsregister finden Kunden und Geschäftspartner nämlich viele wichtige Infos wie Standort, Inhaber und Rechtsform über deine Bäckerei.", "В торговом реестре клиенты и партнёры находят важную информацию, такую как местонахождение, владельца и правовую форму."),
        new("So können Sie sicher gehen, dass deine Bäckerei wirklich existiert, bevor Sie Geschäfte mit dir machen.", "Так они могут убедиться, что твоя пекарня действительно существует, прежде чем вести с тобой дела."),
        new("Außerdem musst du nach §37 A HGB deinen vollständigen Firmennamen auf Rechnungen, E-Mails und anderen Geschäftsbriefen schreiben.", "Кроме того, по §37a HGB ты обязан указывать полное фирменное название на счетах, электронных письмах и другой деловой переписке."),
        new("So wissen deine Geschäftspartner mit wem Sie es zu tun haben.", "Так партнёры знают, с кем имеют дело."),
        new("Nachdem das erledigt ist, beginnt deine Bäckerei zu florieren.", "После этого твоя пекарня начинает процветать."),
        new("Doch irgendwann möchtest du als Bäckermeister auch in den wohlverdienten Ruhestand gehen und deine Tochter soll das Geschäft übernehmen.", "Но однажды ты, как мастер‑пекарь, хочешь уйти на заслуженный отдых, и твою дочь должна принять бизнес."),
        new("Muss sie dann einen neuen Namen wählen?", "Нужно ли ей выбрать новое название?"),
        new("Zum Glück nicht.", "К счастью, нет."),
        new("Denn hier greift der Grundsatz der Firmen Beständigkeit.", "Здесь действует принцип устойчивости фирмы."),
        new("Er erlaubt das Unternehmen, ihren Namen auch nach einem Inhaberwechsel beizubehalten.", "Он позволяет сохранять название даже при смене владельца."),
        new("Das ist nicht nur praktisch, weil ganz viel Bürokram wegfällt, sondern auch sinnvoll.", "Это не только практично, потому что исчезает масса бумажной волокиты, но и разумно."),
        new("Deine Kunden behalten einen vertrauten Namen und es gibt keine unnötige Verwirrung oder dadurch entstehende Umsatzeinbußen.", "Клиенты сохраняют привычное имя, и не возникает лишней путаницы или потери оборота."),
        new("Deine Tochter kann also weiterhin vom guten Ruf der Bäckerei profitieren.", "Твоя дочь может и дальше пользоваться хорошей репутацией пекарни."),
        new("Aber wie sieht es mit dem Namen aus, wenn eine neue Bäckerei mit einem ganz ähnlichen Namen eröffnet?", "Но что, если рядом открывается новая пекарня с очень похожим названием?"),
        new("Eines Tages eröffnet nämlich eine neue Bäckerei gleich um die Ecke, mit dem Namen Gold, Kruste und Co.", "Однажды действительно открывается новая пекарня за углом с названием «Гольд, Крусте и Ко»."),
        new("Ist das erlaubt?", "Это разрешено?"),
        new("Nein.", "Нет."),
        new("Denn laut der Firmenunterscheidbarkeit muss sich der Firmenname deutlich von bestehenden Unternehmen am selben Standort unterscheiden.", "Согласно принципу различимости фирм название должно заметно отличаться от существующих компаний в том же месте."),
        new("Sonst könnten Kunden versehentlich beim falschen Geschäft kaufen.", "Иначе клиенты могут случайно купить в неправильном магазине."),
        new("Oder Behörden würden womöglich Bestellungen, Rechnungen oder sogar Mahnungen an die falsche Firma schicken.", "Или органы власти могут отправить заказы, счета или даже напоминания не той фирме."),
        new("Du kannst also beruhigt sein.", "Так что можешь быть спокоен."),
        new("Gold, Kruste und Co. ist zu ähnlich und das Handelsregister würde den Namen nicht zulassen.", "«Гольд, Крусте и Ко» слишком похоже, и торговый реестр такое название не допустит."),
        new("Eine neue Bäckerei mit dem Namen Müllers Backstube wäre hingegen völlig in Ordnung.", "А вот новая пекарня с названием «Пекарня Мюллера» была бы полностью допустима."),
        new("Aufgrund des Erfolgs deiner Bäckerei möchtest du nun weitere Niederlassungen mit den Namen Meisters, Kruste und Süßesünde Backhauser öffnen.", "Из‑за успеха твоей пекарни ты хочешь открыть ещё филиалы с названиями «Мейстерс», «Крусте» и «Сладкий грех»."),
        new("Klingt kreativ, ist aber nicht erlaubt.", "Звучит креативно, но это запрещено."),
        new("Nach dem Grundsatz der Firmeneinheit in §17 HGB darf ein Unternehmen nicht mehrere unterschiedliche Firmennamen haben.", "Согласно принципу единства фирмы в §17 HGB компания не может иметь несколько разных фирменных названий."),
        new("So ist auch keiner verwirrt.", "Так никто не путается."),
        new("Die Kunden wissen mit wem sie Geschäfte machen und das Finanzamt kann wichtige Dokumente wie Steuer- und Buchungsunterlagen richtig zuordnen.", "Клиенты знают, с кем ведут дела, а налоговая может правильно сопоставлять важные документы, такие как налоговые и бухгалтерские."),
        new("Das bedeutet, du kannst nur weitere Niederlassungen unter dem Namen Gold, Kruste eröffnen.", "Это означает, что ты можешь открывать филиалы только под названием «Гольдкрусте»."),
        new("Prima! Neben dem richtigen Namen ist auch die Wahl der richtigen Betriebsform wichtig.", "Отлично! Помимо правильного названия, важен и выбор правильной организационно‑правовой формы."),
        new("Welche Formen es gibt, zeigen wir dir hier im Video.", "Какие формы существуют, мы покажем в этом видео."),
    };

    public void OnGet() { }
}
